#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
---
- name: Install Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: Start Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
